import { z } from "zod";

export const Persona = z.object({
  _id: z.string(),
  split: z.enum(["train", "heldout", "demo"]),
  caseId: z.string().optional(),
  segment: z.string(),
  opening: z.string(),
  hidden: z.object({
    name: z.string(),
    role: z.string(),
    teamSize: z.number().int().positive(),
    need: z.enum(["sso", "security_review", "integrations", "enterprise", "dashboards", "price_only", "other"]),
    billing: z.enum(["monthly", "annual"]),
    budgetPerSeat: z.number().optional(),
    timeline: z.string(),
    competitor: z.string().optional(),
  }),
  behavior: z.object({
    leavesIfContactBeforePrice: z.boolean().default(false),
    maxSchedulingExchanges: z.number().int().default(3),
    checksMath: z.boolean().default(false),
    readiness: z.enum(["browsing", "evaluating", "ready"]).default("evaluating"),
  }),
  // Computed in code from `hidden`, never generated by an LLM.
  qualified: z.boolean(),
});
export type Persona = z.infer<typeof Persona>;

export const QUALIFYING_NEEDS = ["sso", "security_review", "integrations", "enterprise"] as const;

export function isQualified(h: Persona["hidden"]): boolean {
  return (h.teamSize >= 20 && (QUALIFYING_NEEDS as readonly string[]).includes(h.need)) || h.teamSize >= 200;
}

export type ToolCallLog = { tool: string; input: unknown; output?: unknown; blockedBy?: string };
export type RuleEvent = { ruleId: string; type: "tool_order" | "limit" | "check"; action: "blocked" | "rewrote" | "passed"; detail?: string };
export type RenderedWidget = { name: string; markdown: string; introducedIn: number };
export type StateSnapshot = Record<string, string | boolean | null>;

export type Turn = {
  role: "customer" | "agent";
  text: string;
  toolCalls?: ToolCallLog[];
  widgets?: RenderedWidget[];
  ruleEvents?: RuleEvent[];
  stateAfter?: StateSnapshot;
  provenance?: number[];
  toolsAvailable?: string[];
  contextLoaded?: string[];
  model?: string;
  costUsd?: number;
  ts: Date;
};

export type Outcome = {
  booked: boolean;
  qualified: boolean | null; // null for live chats with no persona
  success: boolean | null;
  trialSent: boolean;
  left: boolean;
  quoteCorrect?: boolean;
  lockedViolations: number;
  turns: number;
  costUsd: number;
};

export type Labels = {
  intent: string;
  dropStage: string;
  failureType: string;
  pushiness: number;
  violations: string[];
};

export type Conversation = {
  _id: string;
  personaId?: string;
  configVersion: number;
  source: "sim" | "live" | "replay";
  runId?: string;
  seed?: number;
  turns: Turn[];
  outcome?: Outcome;
  labels?: Labels;
  summary?: string;
  createdAt: Date;
};

export type RunTurnInput = {
  conversationId?: string;
  configVersion?: number; // defaults to the active version
  config?: import("./config/schema").AgentConfig; // run an unsaved config (tests); pass it on every turn
  message: string;
  source?: Conversation["source"];
  personaId?: string;
  seed?: number;
  runId?: string;
};

export type RunTurnResult = {
  conversationId: string;
  reply: string;
  widgets: RenderedWidget[];
  state: StateSnapshot;
  toolCalls: ToolCallLog[];
  ruleEvents: RuleEvent[];
  provenance: number[];
  toolsAvailable?: string[];
  contextLoaded?: string[];
  ended: boolean;
};
